apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app_type: {{ .Values.labels.app_type }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: {{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    ports:
    - containerPort: 5672
    - containerPort: 15672
    env:
    - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
      value: "-rabbit allow_remote_guest_access true"
#    resources:
#      limits: 
{{- /* toYaml .Values.resources.limits | nindent 8 */ -}}
#      requests: 
{{- /* toYaml .Values.resources.limits | nindent 8 */ -}}
