apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-dashboard
  namespace: argo-rollouts
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argo-rollouts # Matches the controller labels
  ports:
    - protocol: TCP
      port: 9090          # The port you'll use to access the service
      targetPort: 3100  # The port the dashboard is actually listening on
      nodePort: 30080   # Optional: Pick a port between 30000-32767
