apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app_type: {{ .Values.labels.app_type }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: {{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
    - containerPort: 27017
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
    restartPolicy: Always
