apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-app
  namespace: argocd
spec:
  project: cls-fit

  source:
    repoURL: https://github.com/PullaPantangi/roboshop-k8s-26.git
    targetRevision: master
    path: applications/mongodb

  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

