apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app_type: {{ .Values.labels.app_type }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: {{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    ports:
    - containerPort: 8080
