apiVersion: v1
kind: Pod
metadata:
  labels:  {{- include "roboshop-k8s-26.labels" . | nindent 4 }}
    run: {{ .Values.podLabels | default "alma" }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: {{ .Values.affinity.key }}
            operator: {{ .Values.affinity.operator }}
            values:
            - {{ .Values.affinity.value }}
  containers:
  - image: {{ .Values.image.repository }}/k8s_web:{{ .Values.image.tag }}
    name: {{ .Chart.Name }}
    env:
    - name: HOST_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      requests:
      {{- with .Values.resources }}
        memory: {{ .requests.memory }}
        cpu: {{ .requests.cpu }}
      limits:
        memory: {{ .limits.memory }}
        cpu: {{ .limits.cpu }}
      {{- end }}
  dnsPolicy: {{ .Values.dnspolicy | default "ClusterFirst" }}
  restartPolicy: {{ .Values.restartpolicy | default "Always" }}
